feature/elastic search pull request
aiondemand/AIOD-rest-api pull request #181
Opened 2023-11-09 12:51 UTC by AdrianAlcolea

First elesticsearch service pull request

2023-11-10 10:19 UTC, josvandervelde requested changes
Thanks for this work!
Functionally it looks good, I think! Nicely configured, as far as I can tell.

The code could be cleaner though. Using tooling like black would help (already configured for this project). Generally, there is quite some code duplication, and the creation of the configuration files (conf, sql, json) could be simpler using a templating engine. The current choices make the code harder to maintain, so it would be good to clean it up. In hindsight, it might've helped to discuss architectural decisions (e.g., how to handle the overlap of SQL files) before implementing all of it.

Quite some comments, let me know if there's anything unclear / if you'd like to discuss some points. Thanks!

2023-11-10 10:19 UTC, josvandervelde commented on src/tests/routers/search_routers/test_search_router_datasets.py
> +def test_search_happy_path(client: TestClient):
You're only testing the happy path. I'd suggest testing the exception-handling

2023-11-10 10:19 UTC, josvandervelde commented on src/routers/search_router.py
> +            platforms: Annotated[list[str] | None, Query()] = None,
Do you want to raise an exception on non-existent platforms?

2023-11-10 10:19 UTC, josvandervelde commented on connectors/fill-examples.sh
> +  -c connectors.example.example.ExampleDatasetConnector \
The reason we didn't add the example dataset connector by default, is that dataset is the only resource for which we do have working connectors (e.g. OpenML), and then an example is not really needed anymore.

2023-11-10 12:00 UTC, AdrianAlcolea commented on Dockerfile
> +RUN pip install elasticsearch
Done =)

2023-11-10 12:15 UTC, AdrianAlcolea commented on docker-compose.yaml
> +      test: ["CMD-SHELL", "curl -u elastic:changeme http://localhost:9200/_cat/health | grep -q -E 'green|yellow'"]
Done =)

2023-11-10 12:22 UTC, AdrianAlcolea commented on docker-compose.yaml
> +      dockerfile: curl_dockerfile
Done =)

2023-11-10 12:22 UTC, AdrianAlcolea commented on src/tests/routers/search_routers/test_search_router_events.py
> +    # Get the mocker results to test
Yes, I use to comment a lot XD

2023-11-10 12:30 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +            platforms: Annotated[list[str] | None, Query()] = None,
For that kind of decision we really need to have some talk with everyone that needs the searches, because I actually only saw the marketplace, which has the platforms as a selection list... but maybe from other places they will allow to write them, I don't know

2023-11-10 12:34 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +            platforms: Annotated[list[str] | None, Query()] = None,
In any case, we could raise the exception, but it also imply something... Will we retrieve them from the database to compare with? If we don't, every time we add a new one, we will need to actualise this code too

2023-11-10 12:36 UTC, AdrianAlcolea commented on connectors/fill-examples.sh
> +  -c connectors.example.example.ExampleDatasetConnector \
Ok... do you need me to remove it from the fill-examples.sh file of the search branch?

2023-11-10 12:45 UTC, AdrianAlcolea commented on .env
> +ES_JAVA_OPTS="-Xmx256m -Xms256m"
I receive an "The specified size exceeds the maximum representable size." message with this parameters...
In any case, I can make some comments on the readme with the url so for production the decision will depend on the machines

2023-11-10 12:57 UTC, josvandervelde commented on src/routers/search_router.py
> +            platforms: Annotated[list[str] | None, Query()] = None,
The platforms are already stored in the db

2023-11-16 08:45 UTC, andrejridzik commented on src/routers/search_router.py
> +            page: int = 1,
Can we change the logic to use the standard `limit` + `offset` approach? The current one has some serious limitations as a consequence of page being the size of the limit value..

2023-11-20 13:53 UTC, josvandervelde commented on es/elasticsearch.yml
> +xpack.license.self_generated.type: basic
As discussed with Adrian: currently we're not letting anyone connect with ES directly. As long as that's not the case, any layer of security is a bonus.

2023-11-21 12:39 UTC, andrejridzik commented on src/routers/search_router.py
> +            if offset < 0:
It should be possible to replace this check in the function header
```python
offset: int = Field(default=0, ge=0)
```

2023-11-21 12:39 UTC, andrejridzik commented on src/routers/search_router.py
>              if limit > LIMIT_MAX:
It should be possible to replace this check in the function header
```python
limit: int = Field(default=10, le=LIMIT_MAX)
```

2023-11-21 12:39 UTC, andrejridzik commented on src/routers/search_router.py
> +        resource.aiod_entry = AIoDEntryRead(date_modified=resource_dict["date_modified"])
As a result of this `aiod_entry.status` is always set to "draft". @josvandervelde Perhaps consider setting it as optional?

2023-11-24 14:00 UTC, josvandervelde commented on src/setup/es_setup/generate_elasticsearch_indices.py
> +        es_client.indices.create(index=entity, body=mapping, ignore=400)
Could you add a comment describing why you want ES to ignore 400-errors?

2023-11-24 14:01 UTC, josvandervelde commented on src/setup/es_setup/generate_elasticsearch_indices.py
> +def generate_mapping(entity, fields):
`entity` is unused

2023-11-24 14:07 UTC, josvandervelde commented on src/setup/es_setup/generate_elasticsearch_indices.py
> +        mapping = add_field(mapping, field)
You're passing the dictionary to another function that creates a deepcopy and adds fields and returns it. Instead, it's much more readable (I think) to do this:


```def generate_mapping(fields):
    mapping = copy.deepcopy(BASE_MAPPING)
    for field_name in fields:
        mapping["mappings"]["properties"][field_name] = {
            "type": "text",
            "fields": {"keyword": {"type": "keyword"}},
        }
    return mapping
```

2023-11-24 14:09 UTC, josvandervelde commented on src/setup/logstash_setup/generate_logstash_config_files.py
> +    entities = {}
Can be simplified, see comment for generate_elasticsearch

2023-11-24 14:13 UTC, josvandervelde commented on src/setup/logstash_setup/generate_logstash_config_files.py
> +    os.makedirs(config_path, exist_ok=True)
This code can be a bit simplified, and easier to read using `Pathlib`:

```
    path_base = Path("/logstash")
    path_base_config = path_base / "config"
    path_pipeline_config = path_base / "pipeline" / "conf"
    path_pipeline_sql = path_base / "pipeline" / "sql"
    for path in (path_base_config, path_pipeline_config, path_pipeline_sql):
        path.mkdir(parents=True, exist_ok=True)
```

2023-11-24 14:17 UTC, josvandervelde commented on src/setup/logstash_setup/generate_logstash_config_files.py
> +    pipeline_config_path = os.path.join(base_path, "pipeline", "conf")
It would be better to define all these constants as global variables, outside of this function (capitalized, e.g. `PATH_BASE` and `PATH_CONFIG_SYNC_FILE`). This makes the function itself smaller and more readable

2023-11-24 14:21 UTC, josvandervelde commented on src/setup/logstash_setup/generate_logstash_config_files.py
> +    pipeline_config_files_data = {
You don't have to redefine the data dictionary. You can use the same dictionary for both templates - `jinja2` doesn't mind having additional parameters defined in the `render` function that aren't used.

I would just rename it to `render_parameters` by the way, instead of `pipeline_config_files_data` (for me this naming is not very clear)

2023-11-24 14:24 UTC, josvandervelde commented on src/setup/logstash_setup/config_file_template.py
> +CONFIG_FILE_TEMPLATE = """http.host: "0.0.0.0"
could you move all the templates to a separate package? e.g. `logstash_setup/templates`?

2023-11-24 14:25 UTC, josvandervelde commented on src/setup/es_setup/definitions.py
> +BASE_MAPPING = {
You haven't added a `__init__.py` to `setup`

2023-11-24 14:32 UTC, josvandervelde commented on src/setup/logstash_setup/generate_logstash_config_files.py
> +            pipeline_sql_init_file_path, PIPELINE_SQL_INIT_FILE_TEMPLATE, pipeline_sql_files_data
For me, the naming is a bit off. It's very long, and for me not very clear. For me it would also be easier to read if the similar calls are all beneath eachother.

What about

```
file_path_init = PATH_SQL / f"init_{entity}.sql"
file_path_sync = PATH_SQL / f"sync_{entity}.sql"
file_path_rm = PATH_SQL / f"rm_{entity}.sql"
generate_file(file_path_init, TEMPLATE_SQL_INIT, render_parameters)
generate_file(file_path_sync, TEMPLATE_SQL_SYNC, render_parameters)
generate_file(file_path_rm, TEMPLATE_SQL_RM, render_parameters)
```?

You can do something similar with the config, config_init and config_sync (above) I think

2023-11-24 14:46 UTC, josvandervelde commented on docker-compose.yaml
> +        source: ./logstash/pipeline/conf
When I try `docker compose --profile examples up -d` I get an 
`Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /my/path/AIOD-rest-api/logstash/pipeline/conf`

Am I missing something here? Should everyone run the generation-scripts manually, while making sure that they know the right environment variables to set? That makes just running the project a lot more complex. Would it be possible to run the required scripts automatically on `docker compose up`?

2023-11-24 14:48 UTC, josvandervelde commented on .gitignore
> +**.DS_Store
It would be nice to add all generated files to gitignore, so that nobody commits them by mistake.

2023-11-27 13:45 UTC, josvandervelde commented on docker-compose.yaml
> +      - ./data/elasticsearch:/usr/share/elasticsearch/data
Fixed: https://github.com/aiondemand/AIOD-rest-api/pull/181/commits/453b1cd5a66c6f8d335d107e3173fbe8f6ac63e2

2023-11-27 16:57 UTC, josvandervelde commented on src/routers/search_router.py
> +            if offset < 0:
Thanks! fixed in https://github.com/aiondemand/AIOD-rest-api/pull/181/commits/85c76b5ca882d8ba485f8d75b12feab94e4cdd44

2023-11-27 16:57 UTC, josvandervelde commented on src/routers/search_router.py
>              if limit > LIMIT_MAX:
Thanks! fixed in https://github.com/aiondemand/AIOD-rest-api/pull/181/commits/85c76b5ca882d8ba485f8d75b12feab94e4cdd44

2023-11-27 16:59 UTC, josvandervelde approved these changes
Thanks Adrian!
It took some time, but I think it looks good now. Please take a look at my last changes, and let me know if you have any comments!

2023-11-28 10:01 UTC, merged