Create Dev enviroment
aiondemand/AIOD-rest-api pull request #2
Opened 2023-03-09 11:23 UTC by arejula27

When trying to execute the code on my local machine i have some dependency  and problems with my local python installation. 

A Solution that i propose is creating a dev enviroment with docker.  The idea is working within a container similar to the production one. 

For using it is as simple as open the docker dashboard on the dev enviroment section.
![image](https://user-images.githubusercontent.com/46299278/224009094-4f1b871a-df24-4cf8-9e9d-3f1b3ec8c182.png)

2023-03-09 11:35 UTC, arejula27 commented
All test are passed inside the container following the steps:

- Clone the repo
- Open docker dashboard
- Create new dev enviroment from local folder
- Open vscode from docker
![image](https://user-images.githubusercontent.com/46299278/224011534-10bd64cf-8183-40f7-b047-0a0ffece9614.png)
- Run:
```bash 
cd src
pytest
```

2023-03-13 12:53 UTC, gmouchakis commented
@arejula27 I'm not really familiar with Docker Dashboard and its dev environments using VSCode. Is it possible to just run the tests using Docker commands?
Also it would be nice if you could add the instructions in an appropriate README section so one can spot them easily.

2023-03-13 13:04 UTC, arejula27 commented
> @arejula27 I'm not really familiar with Docker Dashboard and its dev environments using VSCode. Is it possible to just run the tests using Docker commands? 

There are previous scripts that allow it. I just added a new option for people who had problems with the installation process and the different python versions. 

>Also it would be nice if you could add the instructions in an appropriate README section so one can spot them easily.

Yes, i will do it when i have time :D

2023-03-13 13:20 UTC, josvandervelde requested changes
Nice addition!
I noticed you forked the project to https://github.com/arejula27/AIOD-rest-api/tree/dev-enviroment, was that intentional?

2023-03-13 13:20 UTC, josvandervelde commented on DevDockerfile
> +COPY ./src /app
Wouldn't it be better not to copy these files, and to add them as a volume in the docker-compose?
This would make sure that the files in the container are updated when you change them locally.

2023-03-13 13:20 UTC, josvandervelde commented on scripts/run_apiserver_dev.sh
> +SRC_PATH="${APP_ROOT}/src"
These variables are not used.

2023-03-13 14:40 UTC, arejula27 commented on scripts/run_apiserver_dev.sh
> +SRC_PATH="${APP_ROOT}/src"
The variables are used for going to the src folder so the command could be `main.py ......`

2023-03-13 14:40 UTC, arejula27 commented on DevDockerfile
> +COPY ./src /app
done

2023-03-13 14:48 UTC, josvandervelde commented on DevDockerfile
> +COPY ./src /app
I see that you've removed

```
WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml


RUN pip install .
RUN python -m pip install ".[dev]"
```
from the docker file. I think you will still want to install all the dependencies in the dockerfile. I think you'd only want to remove COPY ./src /app

2023-03-13 14:52 UTC, josvandervelde commented on scripts/run_apiserver_dev.sh
> +SRC_PATH="${APP_ROOT}/src"
Good point! I missed that

2023-03-13 15:16 UTC, arejula27 commented on DevDockerfile
> +COPY ./src /app
ok, i thought the pyproject was a file that must be only in the project folder, i am not used to develop on python 😅

2023-03-14 08:06 UTC, josvandervelde commented on compose-dev.yaml
> +      source: ~/.ssh/
Last question I think: with which goal do you add the ssh keys of the host machine to the docker container?
If it is for git actions, it should not be necessary, because you could do them as well from your local machine (the `src` folder is mounted)

I think this should be OK since it is a development container that should never be accessed from outside, but if we could as easily not mount the `.ssh`, then my private key would feel a bit safer :)

2023-03-14 08:28 UTC, arejula27 commented on compose-dev.yaml
> +      source: ~/.ssh/
It was for making the git workflow faster, but if we prioritize security i am going to change it back and don't mount the ssh folder

2023-03-14 08:32 UTC, arejula27 commented on compose-dev.yaml
> +      source: ~/.ssh/
It just allow me to do git commits within my IDE, but i could look for other ways or just use an external terminal XD

2023-03-14 15:28 UTC, arejula27 commented on compose-dev.yaml
> +      source: ~/.ssh/
shall i resolve this thread or change the file?

2023-03-14 16:17 UTC, josvandervelde approved these changes

2023-03-14 16:22 UTC, merged