Feature/zenodo uploader
aiondemand/AIOD-rest-api pull request #214
Opened 2023-11-29 17:20 UTC by jsmatias

In summary the endpoint `upload/datasets/{identifier}/zenodo` was created to upload content to zenodo.
The main changes include:
1. The folder `uploader` was renamed to `uploaders` and `zenodo_uploader.py` was created inside.
2. Folder `routers/uploader_routers` was created and file `upload_router_zenodo.py` was created inside.
3. For consistency, the `uploader_router_hugginface.py` file was moved inside and the required modifications were done:
    a. File `uploader_router.py` was created with The abstract class `UploaderRouter`. This was passed as a parent to `UploadRouterZenodo`, as well as to `UploadRouterHuggingface`. The latter was modified to inherit the type of the abstract class and avoid type error with the `router_list` in the `src/routers/uploader_routers/__init__.py` file.
    b. Minor changes were made to the `main.py` to include the new `router_list`
4. Automated tests were created. 

Because the zenodo workflow is a bit complex, I'll summarise it as follows:
1. An empty resource is created or the metadata of an existing one is requested.
2. Metadata is uploaded if necessary
3. A file is uploaded to Zenodo
4. The processes above can be repeated to upload more files to the same resource.
5. Finally, the resource is published. Once this is done, no more files can be uploaded to the same resource.

2023-12-04 13:27 UTC, josvandervelde requested changes
Thanks Jean!
Generally it looks good, no real problems. Just a lot of small comments.

2023-12-04 13:27 UTC, josvandervelde commented on src/tests/uploader/zenodo/test_dataset_zenodo_uploader.py
> +    headers = {"Authorization": "Fake token"}
It would be nice if the test-cases were a bit smaller (less line per test), I think it would be easier to get an overview of the differences between the tests.

For instance, you could define `HEADERS` and `PARAMS_DRAFT` and `PARAMS_PUBLISH` at the top of the file

2023-12-08 13:59 UTC, jsmatias commented on src/routers/uploader_routers/upload_router_zenodo.py
> +                    description="When published, the dataset and files will be publicaly ccessible "
Thanks. 
Yeah, that makes sense.

2023-12-11 08:42 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +        with Session(engine) as session:
Good point. I refactored this part of the code and I included a similar validator for Zenodo with the pattern "^zenodo.org:[1-9][0-9]*$".

2023-12-12 10:27 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +    def _generate_metadata_file(self, dataset: Dataset) -> dict:
Yes, that's better indeed. I fixed it.

2023-12-12 10:29 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +                    if current_zenodo_metadata["state"] == "done":
You're right. Well noticed, thanks!

2023-12-12 10:35 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +    def _get_resource(self, session: Session, identifier: int) -> Dataset:
I created an abstract class as a parent to zenodo and huggingface uploaders. With that we reuse functionalities that are present in both. I tried to change the `hugging_face_uploader` logic as minimum as possible to avoid any unexpected error.

2023-12-12 10:36 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +    def _store_resource_updated(
Same as for `_get_resource`.

2023-12-12 11:55 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +                "content_size_kb": file["filesize"],
Well noticed!

2023-12-12 14:58 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +                "content_url": "",
This is tricky. The `content_url` is in a draft repo while it is not published. I used this URL as a location until the dataset is published. Once everything is published the distributions are updated with the public url.

2023-12-12 15:20 UTC, jsmatias commented on src/tests/uploader/zenodo/test_dataset_zenodo_uploader.py
> +def distribution_from_draft(filenames: list[str]) -> list[dict]:
Good point. I adopted it. :)

2023-12-13 05:16 UTC, jsmatias commented on src/tests/uploader/zenodo/test_dataset_zenodo_uploader.py
> +    with responses.RequestsMock(assert_all_requests_are_fired=False) as mocked_requests:
No reason actually. I just forgot to remove it. Thanks :)

2023-12-14 12:41 UTC, jsmatias commented on src/tests/uploader/zenodo/test_dataset_zenodo_uploader.py
> +def set_up(
A fixture of the DB with all datasets is a bit problematic. In this case I would have to add datasets with different values for the `platform_resource_identifier`. Then, that would require multiple mocked requests for zenodo. 
Instead of doing that I created a few simpler fixtures for datasets and some `db_with_person_and_dataset` when convenient.

2023-12-14 12:58 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +def _wrap_exception_as_http_exception(exc: Exception):
I moved it to a specific file and imported it where it is used.

2023-12-14 16:49 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +            "method": dataset.measurement_technique or "",
I removed it.

2023-12-18 16:06 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +            # "license": dataset.license.name if dataset.license else "cc-zero",
I included a license check to verify if the selected one is allowed to be used to upload content to Zenodo. It covers the licenses for datasets. For other types of resources, they have more types of licenses.

2023-12-19 13:50 UTC, josvandervelde reviewed
Thanks! Looks good - some new comments added

2023-12-19 13:50 UTC, josvandervelde commented on src/uploaders/zenodo_uploader.py
> +            _wrap_bad_gateway_error(msg, res.status_code)
This makes it quite hard to debug. I'd suggest giving the `res` to this function, and add the message to the exception message (or at least log the exception).

Example of an exception from Zenodo:
```
{'status': 400, 'message': 'A validation error occurred.', 'errors': [{'field': 'metadata.version', 'messages': ['Field may not be null.']}]}
```

2023-12-19 13:50 UTC, josvandervelde commented on src/uploaders/zenodo_uploader.py
> +        license_id = self._get_and_validate_license(dataset.license)
version seems to be required as well:

```
{'status': 400, 'message': 'A validation error occurred.', 'errors': [{'field': 'metadata.version', 'messages': ['Field may not be null.']}]}
```

2023-12-19 13:50 UTC, josvandervelde commented on src/routers/uploader_routers/upload_router_zenodo.py
> +        def zenodo_upload(
It would make sense to add authentication and authorization. That seems to be forgotten for HuggingFace, would be good to add there as well.

Maybe check for `has_any_role(KEYCLOAK_CONFIG.get("role"), "upload_zenodo", "upload_zenodo_dataset")` ? (the latest develop has the `has_any_role` function

2023-12-19 13:50 UTC, josvandervelde commented on src/tests/uploader/zenodo/test_dataset_uploader.py
> +            "The dataset must have the name of at least one contact. "
The field `dataset.creator` is checked, although this error message is about `contact` (`dataset.contact` also exists).
Would it make sense to check for `contact`? Maybe bot `contact` and `creator`?

2023-12-19 13:50 UTC, josvandervelde commented on src/routers/uploader_routers/upload_router_zenodo.py
> +            a new repository will be created on Zenodo.
It would be a nice addition to explain to the user what he has to do: first POST a dataset without a platform and platform identifier, but with a name, description, creator (or contact), and version. Then do a POST here. It's possible to change the `publish` status by performing a new POST request (although we might not want to say this last sentence, it's a bit weird to do it - normally you'd expect a PUT, and it's weird that you have to add the file again).

When you're at it, could you add a very small description to HF uploader router as well? Describing you need to create a dataset first?

2023-12-19 13:50 UTC, josvandervelde commented on src/uploaders/zenodo_uploader.py
> +                dataset.platform_resource_identifier = f"zenodo.org:{self.repo_id}"
Nit: it would be nice to raise an error if the platform_resource_identifier is invalid.
Of course this should never happen, but this way we'll make sure that an error is raised upon creation of an identifier that we find invalid (if Zenodo changes the repo_id), rather than when reading than having an invalid resource in our database, that will only throw an error when reading.

I'd suggest moving the `validate_repo_id` inside both the `if` and the `else` statement

2023-12-19 13:50 UTC, josvandervelde commented on src/uploaders/zenodo_uploader.py
> +                dataset.platform = "zenodo"
I like this! We allow users to either specify the platform/platform-id themselves, or we'll generate it.

But... It's different from HuggingFace. There, we expect the user to specify it always. Would it make sense to fix that in this PR? If platform/platform-id is None, set platform to HF and platform_identifier to `f"{username}/{dataset.name}"`? Then we'd have to make sure to throw an error if this leads to an invalid HF identifier (e.g., with spaces) - that error can state something like "We derived an invalid HuggingFace identifier: [derived identifier]. fix this either by changing dataset.name or by adding a correct dataset.platform_identifier"

2023-12-20 12:21 UTC, jsmatias commented on src/error_handlers/error_handlers.py
> +def _wrap_as_http_exception(exception: Exception) -> HTTPException:
I think `as_http_exception` sounds right. 

I was thinking to add more stuff in the module, so I named it as `error_handlers`, but `error_handling` sounds better indeed.
Thanks!

2023-12-20 14:31 UTC, jsmatias commented on src/routers/uploader_routers/upload_router_zenodo.py
> +            a new repository will be created on Zenodo.
Nice, I like the idea of a better explanation to the user. 
Just a clarification here. Zenodo accepts multiple files within the same dataset, in this case, the user sets the field `publish` to `True` only when they want to post the last file. If they want to post just one file and make it public, there's no need to repeat the process. Posting the publishing is done in a single step. 

I'll make everything clear in the documentation. 
Thanks!

2023-12-20 16:47 UTC, jsmatias commented on src/tests/uploader/zenodo/test_dataset_uploader.py
> +            "The dataset must have the name of at least one contact. "
As the field on Zenodo is related to the persons/institutions who created the dataset, I think it makes sense to use the creator only. I'll update error message though.

2023-12-20 21:12 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +                dataset.platform = "zenodo"
Sure. I fixed it and included a `.replace(' ', '_')` to avoid invalid repo_id simply for the presence of empty spaces in the name of the repo.

2023-12-21 11:20 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +            _wrap_bad_gateway_error(msg, res.status_code)
Indeed. I implemented a logic to include the message when it is returned from Zenodo. Some responses may not have a message included if zenodo returns a different status code than the one expected. It's quite unlikely that this case will be triggered, unless zenodo changes something internally. In any case, if that happens the error message will be clear.

2023-12-21 11:34 UTC, jsmatias commented on src/uploaders/zenodo_uploader.py
> +        self.token = token
Thanks for the explanation! I wasn't sure about it, but it totally makes sense.

2023-12-21 11:43 UTC, jsmatias commented on src/uploaders/uploader.py
> +                self.repo_id_validator(repo_id, *args)
Initially I considered it, but because the validator for each sub class could have a different number of arguments, I thought it would be a bit messy to have it. Mypy complains about the method signature not matching to the super class. I managed it using `*args` as an argument for both subclasses. 
Following that I did the same for the `handle_upload` method, I created an abstract method for it for the abstract class `Uploader`.  I think this way the code looks cleaner and easier to devs to implement logic on top of it.

2023-12-21 17:01 UTC, josvandervelde reviewed
Looks good to me!
Some comments about the regex, and it's good to go

2023-12-21 18:51 UTC, jsmatias commented on src/database/validators/zenodo_validators.py
> +repo_id_pattern = r"(?:\Azenodo.org:[1-9]\d*\Z)"
Thanks! I replaced the `\d` by `[0-9]`. 
Regarding the anchors `^` and `$`, they should work as well. I used `\A` and `\Z` because while testing the pattern on regex101.com, the anchors `^` and `$` were matching on after a new line character. But I just realised that this was happening because I had a regex flag `m` set, which is not our case.

In summary, `^` and `$` should work here. I'm reverting the pattern to include instead them of `\A` and `\Z`.

2023-12-21 19:14 UTC, jsmatias commented on src/database/validators/zenodo_validators.py
> +repo_id_pattern = r"(?:\Azenodo.org:[1-9]\d*\Z)"
Another comment here. I just realised that the right pattern should be: `r"^zenodo\.org:[1-9][0-9]*$"`. With `\.` instead of `.`, as this is a counter. I'm fixing it.

2023-12-22 00:34 UTC, jsmatias commented on src/database/validators/zenodo_validators.py
> +pattern = re.compile("|".join([repo_id_pattern, file_id_pattern]))
Basically the identifier `zenodo.org:{id}` is the identifier of a resource on the AIoD, where the `id` is the identifier of the same resource on Zenodo. On the other hand, the distributions have a different identifier pattern on Zenodo, a string including digits and letters, such as this "abcde123-abcd-0000-ab00-abcdef000000".
On AIoD, when the validator checks the platform name and finds `zenodo`, it validates the identifier of the distribution as well. 

I added an explanation of it on the docstring.

2023-12-22 00:35 UTC, jsmatias commented on src/database/validators/zenodo_validators.py
> +
Sorted, thanks!

2023-12-22 00:57 UTC, jsmatias commented on src/uploaders/uploader.py
> +            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.args[0])
In this case, `self._platform_resource_id_validator(repo_id, *args)` are the Zenodo and HuggingFace validator, and both have a prefix msg stating that the `platform_resource_identifier` is invalid for their respective platform names. 

HuggingFace example:
`MSG_PREFIX = "The platform_resource_identifier for HuggingFace should be a valid repo_id. "`

I included the following message at the beginning:
`msg = "The platform_resource_identifier is invalid. "`

2023-12-22 10:31 UTC, josvandervelde approved these changes
Great, looks good!

2023-12-22 10:35 UTC, merged