Fix to intermediate download of a resource's content
aiondemand/AIOD-rest-api pull request #237
Opened 2023-12-19 17:29 UTC by jsmatias

I replaced the `request.get` in the code by `RedirectResponse`. This way the aiod redirects the call to the specific URL to download the content of a resource. Then, the download will be handled on the client side instead of downloading on the server side and passing it to the client.

2023-12-20 15:18 UTC, josvandervelde requested changes
Nice idea, unfortunately I'm afraid it's not working as we'd like, see comments

2023-12-20 15:18 UTC, josvandervelde commented on src/routers/resource_ai_asset_router.py
> +            return RedirectResponse(url=url, status_code=status.HTTP_303_SEE_OTHER, headers=headers)
The headers are not doing anything. It's explained quite well here: https://stackoverflow.com/questions/7583461/redirect-to-page-and-send-custom-http-headers/41218304#41218304 

I tested this using a Zenodo upload. It has `"name": "croissant(11).json"` in the `distribution`. It should get a "Content-Disposition" header with `"attachment; filename=croissant(11).json"`. But it get's an `inline` header if I GET http://localhost/datasets/v1/1/content, which is what you get from Zenodo.

I don't see any possibility to "force" the headers. We redirect the user, and then Zenodo (or whatever platform) controls the response. If this is true, we should probably remove the headers..

2023-12-21 15:11 UTC, jsmatias commented on src/routers/resource_ai_asset_router.py
> +            return RedirectResponse(url=url, status_code=status.HTTP_303_SEE_OTHER, headers=headers)
Indeed, I removed the headers in this case.

2023-12-21 15:12 UTC, jsmatias commented on src/routers/resource_ai_asset_router.py
> +                "Content-Disposition": ("attachment; " f"filename={filename or url.split('/')[-1]}")
Nice spotted! The strings were displaced in two lines and I missed it when I placed them in a single line.

2023-12-21 16:26 UTC, josvandervelde approved these changes
Looks good to me! One minor comment.

It's a shame that's it not possible to keep the headers (I really like the earlier headers) but this is better.

2023-12-21 16:26 UTC, josvandervelde commented on src/tests/routers/ai_asset_routers/test_router_aiassets_retrieve_content.py
> +    assert response.status_code == status.HTTP_303_SEE_OTHER, response.status_code
It's probably good to test the `response.headers["location"]` , at least once

2023-12-21 18:07 UTC, jsmatias commented on src/tests/routers/ai_asset_routers/test_router_aiassets_retrieve_content.py
> +    assert response.status_code == status.HTTP_303_SEE_OTHER, response.status_code
This is already included on test functions:
- `test_endpoints_when_single_distribution`,
- `test_endpoints_when_two_distributions`

2023-12-21 18:13 UTC, merged