Automated Backup System via Docker and Cron
aiondemand/AIOD-rest-api pull request #275
Opened 2024-02-23 10:27 UTC by jsmatias

This backup system is designed to run within a Docker container using Cron jobs to schedule regular executions. 

**In summary, it includes:**

- **Dockerized Backup Solution**: Encapsulates the backup logic within a Docker container.

- **Cron Job Scheduling**: Utilises cron for scheduling backups at regular intervals. This approach provides flexibility in how frequently backups are performed, catering to the specific needs of each service (MySQL, Keycloak, connectors).

- **Incremental Backups**: It uses incremental backup logic implemented in cycles. Each cycle contains a full backup followed by incremental ones. Currently, it is set to run daily in weekly cycles.   

- **Restoring procedure**: The _restore.sh_ script is available to be run manually if any file needs to be restored.

2024-02-23 10:31 UTC, jsmatias commented on src/tests/resources/connectors/zenodo/list_records_2.xml
These changes were made just to make vscode to stop complaining about not listed `resourceTypeGeneral`.

2024-02-23 11:19 UTC, PGijsbers requested changes
Some minor suggestions. Mainly regarding documentation of the cycle functionality. The implementation seems OK. Did not try to run this yet.

2024-02-23 11:19 UTC, PGijsbers commented on backups/backup.sh
> +  echo "Usage: $0 path/to/data path/to/backup/dir <cycle length:int>"
I think it would be good to give a little more documentation about cycle length.

2024-02-23 11:19 UTC, PGijsbers commented on src/tests/backups/test_backup_scripts.py
> +            backup_cycle_0_path / "original1.tar.gz",
I assume this would be a file of insignificant size as there is no delta between the first and second backup?

2024-02-23 11:19 UTC, PGijsbers commented on backups/backup.sh
> +  echo "Usage: $0 path/to/data path/to/backup/dir <cycle length:int>"
and a link to e.g., https://www.gnu.org/software/tar/manual/html_section/Incremental-Dumps.html

2024-02-23 11:19 UTC, PGijsbers commented on src/tests/backups/test_backup_scripts.py
> +            backup_cycle_0_path / "original.snar",
It looks like you can delete this file after completing a full cycle? Though keeping it around probably doesn't hurt as it should only be meta-data. Keeping it also reduces the complexity of the script and potentially allows for continued backups at a higher level.

2024-02-26 10:19 UTC, jsmatias commented on backups/entry.sh
> +/usr/sbin/cron -f -l 4
That sounds good, I'll do it.

2024-02-26 10:24 UTC, jsmatias commented on backups/backup.sh
> +
I agree. It just got longer than I anticipated. In principle it should be just a simple `tar` command plus a few conditions. When I realised it was already around 100 lines. I'll pay better attention for future ones.

2024-02-26 10:30 UTC, jsmatias commented on src/tests/backups/test_backup_scripts.py
> +        assert not os.path.exists(restored_file1_path), f"{restored_file1_path} shouldn't be here."
Well noticed! Thanks, I replaced it.

2024-02-26 10:41 UTC, jsmatias commented on src/tests/backups/test_backup_scripts.py
> +            backup_cycle_0_path / "original.snar",
Yes, you're correct. For now, I believe it's fine to keep old backups just in case, since we're not yet assessing or validating the metadata quality. In future, it will be better to implement some sort of deletion of older backups, then we would keep just one or a few ones.

2024-02-26 11:28 UTC, jsmatias commented on src/tests/backups/test_backup_scripts.py
> +            backup_cycle_0_path / "original1.tar.gz",
Yes, you're correct. If no change was made to the original files after the backup of level 0 (_original0.tar.gz_), then the next level of backup (_original1.tar.gz_) will be empty. This is information of the state of the last backup is stored in the _.snar_ files.

2024-02-26 11:32 UTC, jsmatias commented on backups/backup.sh
> +  echo "Usage: $0 path/to/data path/to/backup/dir <cycle length:int>"
Sure, thanks. 
I added detailed information about it for both scripts, _backup.sh_ and _restore.sh_.

2024-02-27 16:36 UTC, jsmatias commented
After addressing most of the feedback from previous comments, I encountered an issue where the unit tests for this PR ceased to function correctly, even when using the same commit tag that had previously passed. Furthermore, using a `subprocess` in Python to execute the `tar` command for pytests proved to be suboptimal. This approach introduced a dependency on the operating system hosting the tests, specifically due to the requirement of having GNU tar for this backup service to function correctly.

Considering the critical role of these tests, I've relocated their execution to occur inside the backup container itself, initiated from the entry point. This adjustment ensures that the backup container will only start backup operations once it has successfully passed these tests.

To circumvent the dependency on the host OS having GNU tar installed for the restoration script, I've added an `_entry_restore.sh` script. This script is designed to be executed within the container whenever a backup restoration is needed.

In summary, the following modifications have been implemented:
- Unit tests have been moved to execute from within the container, initiated at the entry point.
- The logic for data restoration has been integrated into the container environment.
- A `readme.md` file has been added to enhance the documentation, providing clear instructions on how to perform backups and restorations.

2024-03-01 16:00 UTC, jsmatias commented on backups/backup.sh
> +  echo "Usage: $0 path/to/data path/to/backup/dir <cycle length:int>"
I also added a README.md to describe the process

2024-03-05 10:42 UTC, PGijsbers requested changes
Hi,

I left some feedback. Overall it looks good. Unfortunately, I couldn't test this that well, it seems that `tar` on macos does not do incremental backups :/ And this does worry me, since it seems that you didn't run this either? Because a critical part of the `mysql_restore` call is missing (the docker container name).

I can test this in a linux environment later, but figured I will send this feedback already.

2024-03-05 10:42 UTC, PGijsbers commented on scripts/mysql_restore.sh
> +docker exec -i /bin/bash -c "mysql -uroot -p${MYSQL_ROOT_PASSWORD} aiod < /tmp/backup.sql"
```suggestion
docker exec -i sqlserver /bin/bash -c "mysql -uroot -p${MYSQL_ROOT_PASSWORD} aiod < /tmp/backup.sql"
```

2024-03-05 14:25 UTC, jsmatias commented
> Hi,
> 
> I left some feedback. Overall it looks good. Unfortunately, I couldn't test this that well, it seems that `tar` on macos does not do incremental backups :/ And this does worry me, since it seems that you didn't run this either? Because a critical part of the `mysql_restore` call is missing (the docker container name).
> 
> I can test this in a linux environment later, but figured I will send this feedback already.

Indeed, `tar` on MacOS doesn't have incremental backups. But I installed `GNU tar` to to run it locally. 
In fact, the docker container name was missing! Thanks for spotting that. 
What happened is that when I was testing it, I ran the command just once directly from terminal and when I passed the commands to the script I forgot the container's name. I ended up not testing it again, because the process to restore the entire DB takes some time. 

I cleaned up the DB to make it quicker and tested it properly this time.

2024-03-05 14:32 UTC, jsmatias commented on scripts/mysql_restore.sh
> +docker exec -i /bin/bash -c "mysql -uroot -p${MYSQL_ROOT_PASSWORD} aiod < /tmp/backup.sql"
Applied the change in commit a2a6741.

2024-03-05 14:39 UTC, jsmatias commented on scripts/README.md
> +- **Purpose**: Exports a logical backup of the `aiod` database from the SQL server and extracts it to `data/path/mysql_dump`.
Did you mean to add some change here?

2024-03-05 14:43 UTC, jsmatias commented on scripts/README.md
> +### `database-connect.sql`
Good point. I updated the file name as well.

2024-03-05 14:52 UTC, jsmatias commented on scripts/README.md
> +**Warning!** - This deletes all the content in the data/ directory!
Cool! I added it.

2024-03-05 14:55 UTC, jsmatias commented on scripts/realm_export.sh
> +docker cp keycloak:/tmp/aiod.json "$LOCAL_BACKUP_PATH"/aiod.json
Sure, we can do that. 👍

2024-03-05 15:06 UTC, jsmatias commented on scripts/mysql_dump.sh
> +    mkdir "$LOCAL_BACKUP_PATH"
It's fine. This path should be dedicated to the backups only. If a file with same name is there, this should be addressed before proceeding with the backups. This way any conflict can be avoided.

2024-03-05 15:07 UTC, jsmatias commented on scripts/realm_export.sh
> +    mkdir "$LOCAL_BACKUP_PATH"
It's okay, same as above.

2024-03-05 15:26 UTC, jsmatias commented on scripts/restore.sh
> +;;
Indeed. This was a bit messy, I moved it out and replaced it by an `if` statement in the commit [18449b3](https://github.com/aiondemand/AIOD-rest-api/pull/275/commits/18449b3b65707d0b21abd5637f0cce5fe5feb813).

2024-03-05 15:46 UTC, jsmatias commented on src/tests/backups/test_backup_restore.py
> +def test_backup_happy_path():
Yes, the scripts require GNU tar. I added a condition to check if GNU tar is installed and available in the system, otherwise the tests are skipped.

2024-03-05 16:20 UTC, jsmatias commented on scripts/restore.sh
> +done
I agree, this is not very intuitive. I added some comments to the file in commit [3b144ba](https://github.com/aiondemand/AIOD-rest-api/pull/275/commits/3b144bae6543afe1a8c1a80c893c344e9871ec12).

2024-03-06 15:52 UTC, PGijsbers commented on scripts/README.md
> +- **Purpose**: Exports a logical backup of the `aiod` database from the SQL server and extracts it to `data/path/mysql_dump`.
I am not sure (anymore) what happened here. Please ignore - likely an artifact from me restructuring some suggestions half-way through the document.

2024-03-07 15:43 UTC, PGijsbers approved these changes
Got around to testing it (sorry for the delay). Seems to work as expected/described (tested only with the database backup, adding/removing rows). Left minor comments from actually using it, but feel free to merge without a new review round.

2024-03-07 15:43 UTC, PGijsbers commented on scripts/backup.sh
> +
Printing some information on which cycle and level are used will be useful information to have in the logs.

2024-03-07 15:43 UTC, PGijsbers commented on scripts/restore.sh
> +echo "$backup_dir -------> $destination_dir/$data_to_restore"
```suggestion
echo ""
echo "$backup_dir -------> $destination_dir/$data_to_restore"
echo ""
echo "This overwrites all files in the destination directory and deletes the ones which are not in the archive!"
echo "Are you sure you want to proceed? (y/n)"
```

The prompt is easier to miss if it's not the last thing on the screen.

2024-03-07 16:29 UTC, jsmatias commented on scripts/restore.sh
> +echo "$backup_dir -------> $destination_dir/$data_to_restore"
Nice! Good point.

2024-03-08 10:17 UTC, merged