Improvement/privacy issues
aiondemand/AIOD-rest-api pull request #298
Opened 2024-04-19 09:40 UTC by jsmatias

Code update to restrict access to sensitive information of metadata transferred from the former Drupal platform. The revisions includes:

1. Restricting access to entries from the Drupal platform for the fields `name`, `given_name`, and `surname` within the `persons` entity, and the `email` field within `contacts`, exclusively to users possessing the "full_view_drupal_resources" permission.
2. Requiring authentication for accessing the `email` field within `contacts` for other platforms.

2024-04-19 09:43 UTC, jsmatias commented on src/routers/resource_router.py
> +        """Store a resource in the database"""
No change in this method, I just moved it up during clean up.

2024-04-19 10:04 UTC, jsmatias commented on src/routers/resource_router.py
> +                )
For `get_resource` method, only type annotations were added and `self._retrieve_resource` replaced by `self._retrieve_resource_and_check_roles`.

2024-04-19 10:05 UTC, jsmatias commented on src/routers/resource_router.py
>                  )
This piece of code was transferred to `_retrieve_resources` method.

2024-04-19 10:06 UTC, jsmatias commented on src/routers/resource_router.py
> +                    session, pagination, user, platform
Similar implementations as in `get_resource`

2024-04-23 10:41 UTC, PGijsbers requested changes
Some points for discussion/revision. I'll run the code in the next review round.

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_routers/contact_router.py
> +                session.add(email)
Interesting. I would've guessed this is not needed since there is no sync to the database after this point?
If this is needed, does it make more sense to do it "the other way":
 * once: make a masked e-email
 * on startup: fetch the masked e-mail from the database
 * on requests: set the contact e-mail to this masked e-mail
 
That simplifies the code a bit (imo) and reduces the requests.

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_routers/contact_router.py
> +    def _verify_user_roles(
```suggestion
    def _mask_email_if_unprivileged(
```

(and update calls)

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_routers/person_router.py
> +    def _verify_user_roles(person: type[Person], user: User | None) -> type[Person]:
```suggestion
    def _mask_names_if_unprivileged(person: type[Person], user: User | None) -> type[Person]:
```

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_router.py
> +        return self._retrieve_resources(session, pagination, platform)
What do you think about structuring it something like (edit: read also comment below):

```python
# ResourceRouter
def _retrieve_resources(...):
  ...
  [resource] = self._post_process([resource], session, user)  # convert to list to avoid multiple signatures, other syntax is fine too
  return resource

def _retrieve_resources(...):
  ...
 return self._post_process(resources, session, user)
 
def _post_process(resources, session, user):
  return resources  # Child classes can implement filters or masks here
  
 # Children, e.g. contact
 def _post_process(resources, session, user):
   def _mask_contact(contact):
      ...
   return [_mask_contact(contact) for contact in resources]
```

The nice thing is that the signature is clearer for the child classes: they don't have to think about calling a `super()._retrieve...` and it is immediately clear (i hope) that it just adds something _after_ fetching data. You could even call it `mask_or_filter` instead of `post_process`, but I don't know what other operations might be carried out. If something new pops up, then it is at least immediately clear where it should be added.

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_router.py
> +                    resource: Any = self._retrieve_resource(session, identifier)
Not introduced by this PR. At first glance it looks like the only protection for overwriting asset data is on an entity-type level. So if credentials A and B can both edit datasets, then A can even edit B's datasets. I'll look at this more - but perhaps you already know whether or not this is the case? That does not seem very sensible (users should only be able to edit their own assets, unless they are member of some more privileged group).

2024-04-23 10:41 UTC, PGijsbers commented on src/routers/resource_router.py
> +        return self._retrieve_resources(session, pagination, platform)
Hm. It looks like this does not quite work nicely with the `PUT` requests, especially given that (I think) someone can edit a resource without being privileged enough to see the sensitive information.

2024-04-29 14:36 UTC, jsmatias commented on src/authentication.py
> +        )
Nice! Much better actually. Thanks :)

2024-04-30 14:03 UTC, jsmatias commented on src/routers/resource_routers/contact_router.py
> +    def _verify_user_roles(
Implemented the `_mask_or_filter` method suggested below.

2024-04-30 14:36 UTC, jsmatias commented on src/routers/resource_router.py
> +        self, identifier: str, schema: str, user: User | None = None, platform: str | None = None
Yes. In this context, `Depends` is used by FastAPI to call the `get_user` functions when the user sends a request to the endpoint. This method `self.get_resource` is used inside the scope of the function `get_resource` (they have same name) attributed to the endpoint parameter of `.add_api_route`:
```python
router.add_api_route(
            path=url_prefix + f"/{self.resource_name_plural}/{version}/{{identifier}}",
            endpoint=self.get_resource_func(), # get_resource_func is called here returning get_resource function
            ...
        )
# ...
def get_resource_func(self):
        """
        Return a function that can be used to retrieve a single resource.
        This function returns a function (instead of being that function directly) because the
        docstring and the variables are dynamic, and used in Swagger.
        """

        def get_resource(
            identifier: str,
            schema: self._possible_schemas_type = "aiod",  # type: ignore
            user: User | None = Depends(get_user_or_none),  # Depends is set here
        ):
            resource = self.get_resource(
                identifier=identifier, schema=schema, user=user, platform=None # User is already retrieved by FastAPI at this point.
            )
            return self._wrap_with_headers(resource)

        return get_resource   
...

```

2024-05-01 13:29 UTC, jsmatias commented on src/routers/resource_routers/contact_router.py
> +                session.add(email)
Actually I found the cause of it and a way to work around. This problem occurs when it tries to add the email_mask to more than one contact within the same session. The problem happens because `Session` from `sqlalchemy` has an `autoflush` parameter set to `True` as default. The `flush` perform validations, thus complaining that `email_mask` is already created. 
To fix it, I set `autoflux` to `False` during the session instantiation for the scope of the `get_resources`. 
```python
@contextmanager
def DbSession(autoflush: bool = True) -> Session:
    session = Session(EngineSingleton().engine, autoflush=autoflush)
    try:
        yield session
    finally:
        session.close()
...
 def get_resource(
        self, identifier: str, schema: str, user: User | None = None, platform: str | None = None
    ):
        """
        Get the resource identified by AIoD identifier (if platform is None) or by platform AND
        platform-identifier (if platform is not None), return in given schema.
        """
        _raise_error_on_invalid_schema(self._possible_schemas, schema)
        try:
            with DbSession(autoflush=False) as session:
                resource: Any = self._retrieve_resource_and_check_roles(
                    session, identifier, user, platform=platform
                )
                if schema != "aiod":
                    return self.schema_converters[schema].convert(session, resource)
                return self._wrap_with_headers(self.resource_class_read.from_orm(resource))
        except Exception as e:
            raise as_http_exception(e)
```

2024-05-02 08:30 UTC, jsmatias commented on src/routers/resource_router.py
> +                    resource: Any = self._retrieve_resource(session, identifier)
Yeah, you're correct. Right now there's nothing preventing that to happen. We should store the ownership of an asset using the user's id from Keycloak when a dataset is created in the catalogue. This will prevent an user A to edit any asset belonging to user B.

2024-05-02 08:46 UTC, jsmatias commented on src/database/model/platform/platform_names.py
>      example = "example"
I included `drupal` here because this endpoint - `platforms/{platform_name}/{assets}/v1/{platform_resource_identifier}` - validates `platform_name` against this class. I'm not sure that we want this validation though. This is preventing an user to retrieve an asset from new platforms, such as "aida_cms", "bonseyes", etc.

2024-05-02 08:55 UTC, jsmatias commented on src/routers/resource_router.py
> +        return processed_resource
I decide to keep these methods `_retrieve_resource(s)_and_post_process` because the method `_retrieve_resource` is used in `put_resource` and `delete_resource`. These methods will require a different kind of validation to make sure the user has enough privilege to edit or delete a resource.

2024-05-02 09:04 UTC, jsmatias commented on src/tests/routers/resource_routers/test_router_dataset_generic_fields.py
I increased this time to `0.2` because it started randomly failing (with assert time being < 0.16) when triggered during pre-commit locally. But, honestly, I am not completely sure that I understood the purpose of this time being set as 0.1.

2024-05-03 08:32 UTC, PGijsbers commented on src/routers/resource_router.py
> +        self, identifier: str, schema: str, user: User | None = None, platform: str | None = None
I missed that, thanks!

2024-05-03 08:42 UTC, PGijsbers commented on src/routers/resource_router.py
> +                    resource: Any = self._retrieve_resource(session, identifier)
This I think this should be captured by the `aiod entry`. It currently only lists the editor as a `Person`, which is not linked to keycloak in any way. We do not currently have any relation between keycloak users and the metadata catalogue database, do we?

2024-05-03 08:43 UTC, PGijsbers commented on src/database/model/platform/platform_names.py
>      example = "example"
It looks like the validation should happen against the platforms in the database, not the platforms in this class. From the description, this enum is simply to automatically populate the database if it's started empty.

2024-05-03 08:44 UTC, PGijsbers commented on src/database/model/platform/platform_names.py
>      example = "example"
(but let's do that as a separate PR)

2024-05-03 08:44 UTC, PGijsbers commented on src/routers/resource_router.py
> +                    resource: Any = self._retrieve_resource(session, identifier)
(but let's turn that into an issue and do that as a separate PR)

2024-05-03 08:45 UTC, PGijsbers commented on src/routers/resource_router.py
> +        return self._retrieve_resources(session, pagination, platform)
Ok let's turn that into an issue and do that as a separate PR

2024-05-03 08:54 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_router_dataset_generic_fields.py
I think the main things to test are:
 - the `date_created` is not changed on an update
 - the `date_modified` is updated
 
Something like
```
assert is_close(date_created, datetime_create_request)
assert is_close(date_modified, datetime_update_request)
assert date_created < date_modified
```
would express this better and allows `is_close` to be updated consistently across tests. For example, we had a similar issue before in `openml-python`, and actually found that it often due to OS differences!

Let's see if there are similar tests elsewhere and update them at once together in a separate PR. For this PR, the 0.2 is fine.

2024-05-03 09:26 UTC, PGijsbers reviewed
Overall looks good to me. Minor remarks but we can probably merge otherwise.

2024-05-03 09:26 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_router_contact.py
> +    )
```suggestion
    guest_response_json = guest_response.json()
    if not isinstance(guest_response_json, list):
        guest_response_json = [guest_response_json]
```

2024-05-03 09:26 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_router_contact.py
> +    guest_response = client.get("/contacts/v1", headers=headers)
I interpreted "guest" in the other test to mean "unauthenticated".  If this is the case, then it would make sense to name this differently.

2024-05-08 09:44 UTC, jsmatias commented on src/routers/resource_router.py
> +                    resource: Any = self._retrieve_resource(session, identifier)
> This I think this should be captured by the `aiod entry`. It currently only lists the editor as a `Person`, which is not linked to keycloak in any way. We do not currently have any relation between keycloak users and the metadata catalogue database, do we?

No, at the moment there's nothing linking keycloak users to anything in the metadata catalogue DB. I'll open a new issue for this so we look into it in a new PR.

2024-05-08 09:57 UTC, jsmatias commented on src/routers/resource_router.py
> +        return self._retrieve_resources(session, pagination, platform)
I'm opening an issue for this purpose.

2024-05-08 10:05 UTC, jsmatias commented on src/database/model/platform/platform_names.py
>      example = "example"
> It looks like the validation should happen against the platforms in the database, not the platforms in this class. From the description, this enum is simply to automatically populate the database if it's started empty.

Exactly, I'm opening a new issue for it.

2024-05-08 10:31 UTC, jsmatias commented on src/tests/routers/resource_routers/test_router_dataset_generic_fields.py
I opened an issue for this (#309).

2024-05-08 10:50 UTC, jsmatias commented on src/tests/routers/resource_routers/test_router_contact.py
> +    guest_response = client.get("/contacts/v1", headers=headers)
You're correct, I renamed it.

2024-05-08 12:40 UTC, PGijsbers approved these changes

2024-05-08 12:43 UTC, merged