initial commit for organizations
aiondemand/AIOD-rest-api pull request #30
Opened 2023-04-10 13:43 UTC by antonis96

2023-04-12 11:27 UTC, josvandervelde requested changes
Overall I think it looks good! Some minor points

2023-04-12 11:27 UTC, josvandervelde commented on src/database/model/organization.py
> +    alternate_name: Mapped[str] = mapped_column(String(500), nullable=True,default=None)
Not really part of this PR, but I think that we should really prioritize fixing the `AIResource`. This field, for example, will probably be part of `AIResource`. The sooner we move the fields, the easier it is :)

2023-04-12 11:27 UTC, josvandervelde commented on src/routers/organization_router.py
> +        return "organization"
In UK English, `organisation` is more standard. In American English, `organization` is.
The metadata sheet talks of `organisation`. For an EU project, I think it would be better as well to use UK English, but we're not doing that consequently, also not in our documents.

I'd suggest changing this to `organisation` anyway, I've asked a question on slack to be sure

2023-04-12 11:27 UTC, josvandervelde commented on src/database/model/agent.py
> +    __abstract__ = True
A lot of times, a resource will have a relationship towards a Organization or Person. (e.g. `Dataset.creator`)
Should we therefore make this a separate table instead of an abstract ORM class, similarly to our reasoning with `AIResource`?

I'm not saying we should, but I want to make sure that we've thought about it

2023-04-12 11:27 UTC, josvandervelde commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
Should this indeed be a required, free-format field?

2023-04-12 11:27 UTC, josvandervelde commented on src/schemas.py
> +    type: str = Field(max_length=500)
This field is not very clear to me, and also not described in the Metadata schema. 
Is this again part of the CMS, and should I ignore it for now? Otherwise, I think this should be an enum (or rather a separate table)

2023-04-12 11:27 UTC, josvandervelde commented on src/schemas.py
> +        description="Identifiers of AIodOrganisation that are members of this organization",
Should this be a list of Agents? Then we can also put `Person` in here

2023-04-12 12:05 UTC, antonis96 commented on src/database/model/organization.py
> +    alternate_name: Mapped[str] = mapped_column(String(500), nullable=True,default=None)
I completely agree with you!

2023-04-12 12:37 UTC, antonis96 commented on src/routers/organization_router.py
> +        return "organization"
I changed everything into `organisation`. 
We can always revert if we get a different answer from slack.

2023-04-13 09:46 UTC, josvandervelde commented on src/database/model/agent.py
> +class OrmAgent(UniqueMixin, Base):
Agree! But there is a subtle difference between `OrmResource` and `OrmAIResource`. So it should not be part of the AIResource, but it could be of `OrmResource`.

2023-04-13 09:47 UTC, josvandervelde commented on src/database/model/organization.py
> +    dissolution_date: Mapped[str] = mapped_column(
Great! I just found out that schema.org is not even consistent. It uses `Dataset.date_modified` but `Event.start_date`...
So I'm not sure what's better, I'm fine with either :)

2023-04-13 09:50 UTC, josvandervelde commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
Hmm we still have the problem of two sources of truth: the CMS spreadsheet and the AIoD Metadata schema.
If both are different, I'd suggest following the AIoD Metadata schema. Should we discuss this in the next metadata meeting?

2023-04-13 09:51 UTC, josvandervelde commented on src/schemas.py
> +        description="Identifiers of AIodOrganisation that are members of this organization",
Yes, sounds good! Then we have to change the `OrmAgent` to be a separate table (as discussed in other comment)

2023-04-19 13:20 UTC, antonis96 commented on src/schemas.py
> +        description="Identifiers of AIodOrganisation that are members of this organization",
It's done. Maybe we can proceed with merging.

2023-04-19 14:05 UTC, josvandervelde commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
So what do you think about this? Do you agree that it's not ideal to have two sources of truth? Could we move to the AIoD metadata schema as source of truth, and ignore the CMS spreadsheet? Do you have a suggestion?

2023-04-19 14:07 UTC, josvandervelde commented on src/schemas.py
> +        description="Identifiers of AIodOrganisation that are members of this organization",
Looks good! Only the previous point is still open (I think), about the CMS spreadsheet vs AIoD Metadata

2023-04-19 14:48 UTC, antonis96 commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
I agree with you that it would be much more convenient to have a single source of truth.
Metadata group is currently working on unifying the two spreadsheets. 
When they finalize the schema we will have only one source of truth, the metadata schema. 
Till then,  we can't ignore fields coming from CMS since we will need to support CMS as well.

2023-04-19 15:41 UTC, josvandervelde commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
I agree we need to support it. But in the sense that we can convert the CMS resources to ours, and that we are able to put all info in the CMS in AIoD (right?). That does not mean that we have to copy it 1:1. There can fields with different names from the CMS.

The approach I would like to suggest: use the fields that are defined in the Metadata Spreadsheet. If there are any fields that are in the CMS, but not in the spreadsheet, we add them to the spreadsheet (maybe renaming them a bit, so that they fit into naming-styles that schema.org tend to use).

If there are any fields that are both in the Metadata Spreadsheet and in the CMS, but with different names, we should (I think) use the names of the Metadata Spreadsheet. 

In this case (`connection_to_ai`), this is a weird one for me. I think we should not make it required (even if it's required in the CMS), and I think it would be nice to have a separate table with the enum-values in the DB. Free-format seems a bit weird for such a field, that will make it difficult to search for / filter on.

2023-04-20 14:03 UTC, gmouchakis commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
@josvandervelde I agree with the proposed aproach. We added the relevant fields to the metadata schema along with comments explaining their necessity relateted to the CMS. On top of that we are in conctact with the metadata group regarding other similar fields. The group has decided to release the first version of the schema on 15/5 so I believe that after we have a stable schema version we should reiterate our work on the API, make sure that everything is aligned with the schema and then release API's 1.0 version.

2023-04-20 14:10 UTC, antonis96 commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
With `connection_to_ai` field we are trying to explain how an organisation is "doing AI things". So in this case we are not talking about an enumerated value.
I think it's a good idea to replace enum-values should  with separate tables. Since those fields appear and on other entites as well, i suggest creating a separate issue about that and work it on a new PR

2023-04-21 10:08 UTC, josvandervelde commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
Great! Good points, and thanks for adding the information to the metadata spreadsheet, looks good!
I would suggest changing the field to an optional field (I think we should support adding organisations for which this `connection_to_id` is unknown) and then merge this PR :)

2023-04-21 10:35 UTC, antonis96 commented on src/schemas.py
> +    connection_to_ai: str = Field(max_length=500)
fixed (here)[https://github.com/aiondemand/AIOD-rest-api/commit/00a517cd9d329bdb0f43fc5206a9ca5258175f4c]

2023-04-21 13:01 UTC, josvandervelde approved these changes

2023-04-21 13:19 UTC, merged