Update docker workflow
aiondemand/AIOD-rest-api pull request #302
Opened 2024-04-30 15:31 UTC by PGijsbers

This PR updates the docker workflow:

 - The workflow can now also publish images to docker hub under `aiod/metadata_catalogue`. This happens when:
   - A release is made, pushes with tags `latest` and whatever the version tag is e.g., `v1.3.20240308`.
   - Develop is pushed, pushes with tag `develop`
   - The workflow is dispatched through the Actions tab on Github, pushes with the tag provided in the input
 - The workflow can update the description of that repository, based on the content of `docker-description.md`
 - Using the workflow dispatch, can also update the repository description(s) without updating any image.
 

A build cache is used to avoid double work between `build` and `push` jobs, but it seems to persist between workflows so this hopefully also speeds up the workflow. Otherwise, I would expect a slight slowdown as splitting the workflow into separate jobs (which run on separate runners), means we have to import/export the image from `build` to `test`.

I had hoped to be able to push the built image from `build` directly without rerunning build. While it uses cache now, and thus shouldn't take too much extra time, this largely negates the benefit of splitting `build` and `test`. I would consider merging those jobs again as it should result in a speed up, though it 'feels' nice that the jobs are now separate.

> [!warning]
> **Before merging**, I still want to verify that the `develop` and `release` triggers and flow are set up appropriately. I will do this on a fork. But I don't suspect any (major) changes.

2024-05-02 11:19 UTC, jsmatias requested changes
I left two minor comments here for you to review. Nice job. :)

2024-05-02 11:19 UTC, jsmatias commented on .github/workflows/dockerized-tests.yml
>        - 'Dockerfile'
Should we specify the branch as `develop` on `pull_request` trigger? I think it makes sense to have tests at every PR, but does it make sense to have images being pushed to docker hub if a PR is eventually done to another branch?

2024-05-02 11:19 UTC, jsmatias commented on docker-description.md
> +Please refer to the documentation in the readme of the ["AIOD-rest-api"](https://github.com/aiondemand/AIOD-rest-api) repository.
A minor suggestion that sounds clearer to me.
```suggestion
This image requires a properly configured database setup to function. Additionally, to have all features working, authentication (via Keycloak) and search (through Elasticsearch) must also be configured. Please refer to the documentation available in the README of the ["AIOD-rest-api"](https://github.com/aiondemand/AIOD-rest-api) repository.
```

2024-05-02 15:42 UTC, PGijsbers commented
I am fairly confident the workflow works as intended, as evidence:

 - https://github.com/PGijsbers/AIOD-rest-api/pull/1 does not trigger the docker workflow 
 - https://github.com/PGijsbers/AIOD-rest-api/pull/2 does trigger the docker workflow, but only executes `build` and `test`
 - A push to develop does [run the workflow](https://github.com/PGijsbers/AIOD-rest-api/actions/runs/8926405408) and determines a `:develop` tag (the workflow fails to authenticate because I did not configure credentials in my fork).
 - A release does [run the workflow](https://github.com/PGijsbers/AIOD-rest-api/actions/runs/8926519132) and determines a `:v*` and `:latest` tag (the workflow fails to authenticate because I did not configure credentials in my fork). Note that this is problematic if we ever were do releases for versions which are not most recent (e.g., bugfix patch on an old release). I don't think this will really come up, and even if so we can trigger the action also from the `Actions` tag to re-release the `:latest` image.
 - A workflow dispatch can be used to [run the workflow](https://github.com/PGijsbers/AIOD-rest-api/actions/runs/8926558203) with the provided tag (in this case `:workflow-dispatch`).
 
 I noticed in the process one time the docker tests failing due to the backup test. I am not sure exactly how that happened. In this case however I did find that it is actually really nice that we split `build` and `test`, since I can re-run just the `test` job independently.
 
 So I think this is good to merge (but please let me know if the open thread is resolved).

2024-05-03 08:14 UTC, jsmatias commented on .github/workflows/dockerized-tests.yml
>        - 'Dockerfile'
Got it!

2024-05-03 08:25 UTC, jsmatias approved these changes
Great job, thanks!

2024-05-03 09:27 UTC, merged