Feature/project
aiondemand/AIOD-rest-api pull request #31
Opened 2023-04-12 08:01 UTC by arejula27

Project schema implemented

2023-04-12 11:41 UTC, josvandervelde requested changes
Looks good! Some minor points

2023-04-12 11:41 UTC, josvandervelde commented on src/database/model/project.py
> +    # partners: Mapped[list[str]] = mapped_column(String(250), nullable=True, default=None)
Is this commented out because we do not have `Person / Organisation` yet? If so, could you add a TODO in the code, so that we won't forget it?

2023-04-12 12:13 UTC, arejula27 commented on src/database/model/project.py
> +    project_description_title: Mapped[str] = mapped_column(String(500), nullable=True, default=None)
I used the fields of the Excell, actually some of them are weird but maybe are because a reason, should I rename it?

2023-04-12 12:13 UTC, arejula27 commented on src/database/model/project.py
> +    # partners: Mapped[list[str]] = mapped_column(String(250), nullable=True, default=None)
Good point

2023-04-12 13:07 UTC, arejula27 commented on src/database/model/project.py
> +    start_date: Mapped[datetime] = mapped_column(Date, nullable=True, default=None)
In the metadas schema excell is written start_date. What should we prioritize, sheme.org or the excell?

2023-04-12 13:10 UTC, arejula27 commented on src/database/model/project.py
> +    total_cost: Mapped[float] = mapped_column(Float, nullable=True, default=None)
from which library?

2023-04-12 13:21 UTC, arejula27 commented on src/database/model/project.py
> +    project_description_title: Mapped[str] = mapped_column(String(500), nullable=True, default=None)
in the excell project_description_title and name are two different fields, maybe are the same or maybe not :s

2023-04-13 08:30 UTC, arejula27 commented on src/database/model/project.py
> +    project_description_title: Mapped[str] = mapped_column(String(500), nullable=True, default=None)
i talked with rafa and told me that both are needed

2023-04-13 09:34 UTC, josvandervelde commented on src/database/model/project.py
> +    start_date: Mapped[datetime] = mapped_column(Date, nullable=True, default=None)
As discussed in slack, I'd suggest adding a comment in the Excel. I think that it would be nice to have similar field names for all resources.

2023-04-13 09:34 UTC, arejula27 commented on src/database/model/project.py
> +    start_date: Mapped[datetime] = mapped_column(Date, nullable=True, default=None)
agree

2023-04-17 14:06 UTC, merged