Feature/search by date
aiondemand/AIOD-rest-api pull request #368
Opened 2024-10-23 11:56 UTC by AdrianAlcolea

2024-10-23 14:27 UTC, PGijsbers reviewed
Some suggestions and questions.

2024-10-23 14:27 UTC, PGijsbers commented on src/routers/search_router.py
> +        """The set of linked fields (those with aiod 'link' relations)"""
Does it make more sense to make this non-abstract? Now you defined `return {}` in a lot of child classes, and those may in fact have linked fields?

2024-10-23 14:27 UTC, PGijsbers commented on src/routers/search_router.py
> +            ] = None,
Perhaps a bit of a nitpick, but consider changing the name. with dates it's typical to talk about "before" and "after" so `modified_before` and `modified_after` may be more intuitive to the user.

2024-10-23 14:27 UTC, PGijsbers commented on src/routers/search_router.py
> +                    date_range["lte"] = date_modified_to
Many times ranges are lower-bound inclusive and upper-bound exclusive. i.e., [01-01-2023 through 01-01-2024) maybe be any time in 2023. This has the advantage that if you page through them in the fashion [A, B), [B, C), [C, D), ... that you don't have any overlap.

2024-10-23 14:27 UTC, PGijsbers commented on src/routers/search_router.py
> +                    query["bool"]["must"] = {"range": {"date_modified": date_range}}
Is it correct that a single must cannot be in a single-element list? Because if it can be, that might make it easier; there is cleaner syntax and you have less types to worry about.

2024-10-23 14:27 UTC, PGijsbers commented on src/routers/search_router.py
> +                setattr(resource, linked_field, [resource_dict[linked_field].split(",")])
split already returns a list. is it intentional to wrap it inside of another list?

2024-10-24 10:20 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +        """The set of linked fields (those with aiod 'link' relations)"""
I call linked field those that, in our database schema, have their own table and are linked to the main entity through another table with both identifiers.
Almost all the entities have some "linked fields", but for the moment no one asked me to include them on the search except for "case_study" (but for example if someone want to search by contact person, I will also use this structure for the rest of entities).
I made it this way to keep the structure generic. Not only the method is generic, but (more important) the function to automatically generate the SQL queries (setup/logstash_setup/generate_logstash_config_files.py). If the method is not present in all the search routers we should include some conditional using the "hasattr()" method.
In any case, for the moment only "case_study" is using it, so if you prefer I can change that (and if in a future more entities will use it I can made it generic again).

2024-10-24 10:27 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +            ] = None,
I used "from" and "to" because that's how Andrej called them (he asked for this functionality). Also I think that he intended to use them as a "range", like "from a start date to an end one".
In any case they can also be used like this with after/before and, as you say, this names will probably be more intuitive, so I will change them.

2024-10-24 10:27 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +                    date_range["lte"] = date_modified_to
Yes, totally agree =)

2024-10-24 10:34 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +                    query["bool"]["must"] = {"range": {"date_modified": date_range}}
I will need to review this. It is true that the syntax has become too much...
The thing is that it is generating one single query adding structures (so it has to respect the previous parts, that may have been included or not, depending on the received parameters).
So either the structure gets "overloaded" or the code will be a nest of conditionals, which I don't like neither.

2024-10-24 10:45 UTC, AdrianAlcolea commented on src/routers/search_router.py
> +                setattr(resource, linked_field, [resource_dict[linked_field].split(",")])
Ups! My bad, not intentional at all XP

2024-10-29 08:32 UTC, PGijsbers requested changes
Overall it looks fine, minor suggestions to make it more user friendly.

2024-10-29 08:32 UTC, PGijsbers commented on src/routers/search_router.py
> +                    description="Search for resources modified after this date (included).",
```suggestion
                    description="Search for resources modified after this date (yyyy-mm-dd, inclusive).",
```

2024-10-29 08:32 UTC, PGijsbers commented on src/routers/search_router.py
> +                    description="Search for resources modified before this date (not included).",
```suggestion
                    description="Search for resources modified before this date (yyyy-mm-dd, not inclusive).",
```

2024-10-29 08:32 UTC, PGijsbers commented on src/routers/search_router.py
> +                ),
Please specify the `Query`'s [`pattern`](https://fastapi.tiangolo.com/reference/parameters/#fastapi.Query) parameter to require the specific string format. That way, users get a clear error when they provide a wrong format instead of an `Internal Server Error`.

2024-10-29 09:45 UTC, andrejridzik commented on src/routers/search_router.py
> +                    description="Search for resources modified before this date (not included).",
I would prefer using term `exclusive` instead of `not inclusive`.

2024-10-29 10:11 UTC, andrejridzik commented on src/setup/logstash_setup/templates/sql_init.py
> +    aiod_entry.date_modified{{extra_fields}}{{linked_fields}}
Just a suggestion to the formatting in order to make it more readable. This can be achieved by using leading commas:
```sql
    ...
    , text.html as 'description_html'
    , aiod_entry.date_modified
    {{extra_fields}}
    {{linked_fields}}
```
We would just need to modify the parameters to much this
```python
render_parameters["linked_fields"] = ", " + "\n    , ".join(formated_linked_fields)
```

2024-10-29 13:59 UTC, PGijsbers commented on src/routers/search_router.py
> +                    description="Search for resources modified before this date (not included).",
Me too, but I suggested that earlier and it wasn't adopted so I suggested this.

2024-10-29 14:06 UTC, PGijsbers approved these changes
I agree with Andrej w.r.t. formatting changes and also the new pattern could be slightly simplified (`r"\d{4}-\d{2}-\d{2}"`) _should_ have the same effect. But I am looking to do a release today/tomorrow, and since these are changes which do not affect functionality, I suggest we process that separately.

2024-10-29 15:43 UTC, merged