Add resource filters to GET endpoints
aiondemand/AIOD-rest-api pull request #381
Opened 2024-10-30 17:45 UTC by andrejridzik

* Adding resource filters based on `aiod_entry.date_modified`: `date_modified_after` and `date_modified_before`
* Making `AIoDEntryORM.date_modified` and `AIoDEntryORM.date_created` required as they are always created automatically using `default_factory`

**TODO:** The `GET /platforms/v1` endpoint and tests are currently failing due to missing `aiod_entry` field. Platforms are currently considered to be Resources even though they do not inherit from the common `AIoDConcept` class.

2024-10-30 17:56 UTC, andrejridzik commented
@PGijsbers There is actually a problem currently that we need to discuss in order to resolve it. As I have mentioned in the description, the issue is that Platforms are also treated a Resources, but they are not inheriting from `AbstractAIResource` and thus not from `Concept` that contains the required `aiod_entry` field. Some posible options:

1. Based on the semantics I would assume that we should treat platforms differently and create the router separately (oppose to dynamic creation as it is now) - this will result in some code duplications
2. We should treat platforms as they are now and inherit from `Concept`
3. Create some new more generic router class `XYZRouter` from which both of the two will inherit (`ResourceRouter` and `"PlatformRouter"`)

2024-10-31 08:52 UTC, PGijsbers commented
I favor option 1. Platforms are different, and I don't think it's likely we will encouter (m)any other entities which are not concepts in the future, so I would not start putting an abstraction layer in place for that.

2024-10-31 09:05 UTC, PGijsbers requested changes
Overall looks good. Some minor suggestions, and we need to add a migration script.

2024-10-31 09:05 UTC, PGijsbers commented on src/database/model/concept/aiod_entry.py
> +    date_created: datetime = Field(default_factory=datetime.utcnow)
Changes to the schema should be accompanied by a database schema migration. See also https://github.com/aiondemand/AIOD-rest-api/tree/develop/alembic

2024-10-31 09:05 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_resource_router.py
> +    assert isinstance(response_json, list) and len(response_json) == expected_count
```suggestion
    assert isinstance(response_json, list)
    assert len(response_json) == expected_count
```

2024-10-31 09:05 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_resource_router.py
> +        ({"date_modified_before": (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")}, 1),
```suggestion
        ({"date_modified_after": (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")}, 0),
        ({"date_modified_before": (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")}, 1),
```

2024-10-31 09:05 UTC, PGijsbers commented on src/tests/routers/resource_routers/test_resource_router.py
> +        ({"date_modified_before": (datetime.today() + timedelta(days=1)).strftime("%Y-%m-%d")}, 1),
The diff looks a bit strange, but I just added a testcase where date_modified_after is not 'today'. Otherwise only the one value is ever tested.

2024-10-31 09:05 UTC, PGijsbers commented on src/database/model/concept/aiod_entry.py
> +    date_created: datetime = Field(default_factory=datetime.utcnow)
I can help with that if needed.

2024-10-31 09:47 UTC, andrejridzik commented
> I favor option 1. Platforms are different, and I don't think it's likely we will encouter (m)any other entities which are not concepts in the future, so I would not start putting an abstraction layer in place for that.

I agree. The only question now is whether we want to keep all the endpoints:
<img src="https://github.com/user-attachments/assets/88200abc-f447-493a-806b-3e5c4847a126" width="300">

I've just discovered that `/counts/platforms/v1` actually doesn't work anyway while returning E500 as platform doesn't have the filed platform 😕. I am not sure how platforms are actually created and if one can just delete one.. I assume not. Can you tell me which endpoints actually make sense and I will add them there. Thanks

2024-10-31 14:53 UTC, PGijsbers commented
Yeah, I noticed that earlier too 😅 I am not sure either who should be able to edit the platforms (we should discuss that in a WP3 meeting if it's not already decided), but that's a permission issue not an endpoint issue (though we probably should either not show "admin-only" endpoints in the docs, or clearly indicate them as such). So I think `count` is the only endpoint which doesn't make much sense. At least not with the "detailed" parameter.

2024-10-31 17:30 UTC, andrejridzik commented
Do we also want to keep the pagination there? If so, should I create a new module `routers/helpers.py` or something like that so it can be reused?

2024-11-01 07:28 UTC, PGijsbers commented
Keeping paginations for consistency is probably good. Extracting it to a separate module seems reasonable.

2024-11-04 14:50 UTC, PGijsbers reviewed
Changes look reasonable, I'll try it out tomorrow.

2024-11-05 08:59 UTC, PGijsbers approved these changes

2024-11-05 08:59 UTC, merged