Fix/flaky test
aiondemand/AIOD-rest-api pull request #387
Opened 2024-11-07 11:05 UTC by PGijsbers

## Change

Working on #378. No changes so far, other than refactoring and using `Path.write_text` instead of `io.write`. 
Setting up PR to test flakiness in CI.

## How to Test

## Checklist
- [ ] Tests have been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] Documentation has been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] A self-review has been conducted checking:
  - No unintended changes have been committed.
  - The changes in isolation seem reasonable.
  - Anything that may be odd or unintuitive is provided with a GitHub comment explaining it (but consider if this should not be a code comment or in the documentation instead).
- [ ] All CI checks pass before pinging a reviewer, or provide an explanation if they do not.

## Related Issues

2024-11-07 11:17 UTC, PGijsbers commented
@andrejridzik Did this test fail consistently for you? Or at least consistently enough that you will have a good indication of whether or not things would be fixed. I cannot reproduce it at all and it now also not failing in CI... which leaves me at a loss. If you _can_ reproduce it consistently, I would appreciate it if you could try and see if the test also fails for you on this branch.

2024-12-02 13:13 UTC, PGijsbers commented on src/tests/backups/test_backup_restore.py
> +    time.sleep(one_ms)
This is the real change. The rest is just refactoring.

2024-12-05 16:44 UTC, andrejridzik requested changes
I am still getting majority of failures with this setup. However, I was able to achieve 0% failure rate (n=100) when these two conditions are met:
1. sleep duration set to `10**-1`
2. sleep moved to other location -> after `file1.unlink()`

Note: I got failure rate 11% when setting the sleep to `10**-2`

2024-12-05 16:44 UTC, andrejridzik commented on src/tests/backups/test_backup_restore.py
> +    file1.unlink()
I did some experiments and got most reliable results when adding the sleep after this line.

2024-12-05 18:30 UTC, PGijsbers commented on src/tests/backups/test_backup_restore.py
> +    file1.unlink()
Interesting... Perhaps we'll need both. I'll move the sleep to where you suggested it and see if that's good enough for CI too (because clearly behavior of CI/CD doesn't match your environment 1:1)

2024-12-10 14:24 UTC, PGijsbers commented
Needed both sleeps. I think should be good to go now @andrejridzik ?

2024-12-11 10:01 UTC, andrejridzik approved these changes

2024-12-11 10:42 UTC, merged