Gets zenodo publications
aiondemand/AIOD-rest-api pull request #4
Opened 2023-03-13 13:37 UTC by arejula27

I have improve  the publication endpoint and implement the zenodo connector fot it. I created some new test and all previous test passed except `src/tests/test_get_publications_of_dataset.py`. If someone can help me I will I would appreciate it :D

2023-03-13 14:13 UTC, josvandervelde requested changes

2023-03-13 14:13 UTC, josvandervelde commented on src/main.py
> +         query = select(PublicationDescription).where(
`PEP 8: E111 indentation is not a multiple of 4`. Did you run `black`, `flake` and `mypy`? This should be done automatically before commit, but it looks like it did not happen. You could run it using `pre-commit run --all-files`

This makes (among other things) sure that we use the same formatting, making collaboration easier.

2023-03-13 14:13 UTC, josvandervelde commented on src/main.py
> +    def get_node_dataset(node: str, identifier: str) -> dict:
naming of function: `publication` instead of `dataset`

2023-03-13 14:13 UTC, josvandervelde commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
8 / 49 tests fail, when I run them locally.

2023-03-13 14:13 UTC, josvandervelde commented on src/main.py
> +            msg= f"Publication '{identifier}' not found in the database.",
This trailing comma leads to returning a tuple instead of  a string. If you remove it, you can delete the brackets from the test code `assert response.json()["detail"] == ["..."]` --> `assert response.json()["detail"] == "..."`

2023-03-13 14:55 UTC, arejula27 commented on DevDockerfile
> +
yes, i wil do it

2023-03-13 14:58 UTC, arejula27 commented on src/database/models.py
> +    doi: Mapped[str] = mapped_column(String(250), nullable=False)
I only included some example fields because I am not sure if the Excel sheet has all the final fields. However, I can add them later if it requires a refactor in the future.

2023-03-13 14:59 UTC, arejula27 commented on src/main.py
> +         query = select(PublicationDescription).where(
ok, sorry

2023-03-13 15:06 UTC, arejula27 commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
As i commented before, this test are `src/tests/test_get_publications_of_dataset.py`. I dont understand it, so  someone can modify it or explain it  to me so i will corrected it

2023-03-13 16:11 UTC, arejula27 commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
I think I will fix them by adding the Excell fields

2023-03-14 08:54 UTC, arejula27 commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
All test passed, there are two pre commit errors due to the long string of titles in zenodo (max char 100). Should i rename the publications ?

2023-03-14 15:28 UTC, arejula27 commented
New tests implemented, all operations (GET,POST,PUT, DELETE) over publications

2023-03-14 16:29 UTC, josvandervelde commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
You could break up the strings like this:
```
    def fetch_all(self, limit: int | None) -> Iterator[PublicationDescription]:
        yield from [
            PublicationDescription(
                title="Student-Centred Studio Environments: A Deep Dive into Architecture"
                "Students' Needs",
                doi="10.5281/zenodo.7712947",
                node="zenodo",
                node_specific_identifier="7712947",
            ),
            PublicationDescription(
                title="[Supplementary Materials] De-escalation of asymptomatic testing and "
                "potential of future COVID-19 outbreaks in U.S. nursing homes amidst rising "
                "community vaccination coverage: a modeling study",
                doi=" 10.5281/zenodo.6306305",
                node="zenodo",
                node_specific_identifier="6306305",
            ),
        ][:limit]
```
I've no idea why black doesn't do that automatically, but like this it works.
You then only have to change `import typing` into `import typing  # noqa:F401 (flake8 raises incorrect 'Module imported but unused' error)` in `connectors.__init__.py`, and the project should be green!

2023-03-15 11:20 UTC, arejula27 commented on src/tests/test_get_publication.py
> +from database.models import PublicationDescription, DatasetDescription
done!

2023-03-16 13:38 UTC, josvandervelde requested changes
Looks good!
In the dataset-metadata format, I made some changes that we might want to mirror for the publications as well (depending on that PR). For instance, returning the same object from `fetch` and `fetch_all`, making sure that this is not the database object but the AIoD-schema object, creating separate converter, and moving the testing of the connectors to test/connectors instead of "integration testing" the main. 

I suppose that it's easiest if we merge this PR, and then fix the issues that relate to the dataset PR in a separate PR

2023-03-16 13:38 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_publication_connector.py
> +            node_specific_identifier=publication.node_specific_identifier
I think that other fields, such as the (url, name, filetype) of the linked files are also interesting. 
Maybe datetime_created, datetime_updated, version (I think they call it revision in Zenodo) creators, description, journal, keywords, resource_type, license as well?

Heads up: some of these (Licesnse, keywords) I already implemented for dataset (see dataset PR)

2023-03-16 13:38 UTC, josvandervelde commented on src/main.py
> +                        detail="There already exists a dataset with the same "
This should be `publication` instead of `datset`. Also in the variable names

2023-03-16 13:38 UTC, josvandervelde commented on src/tests/test_post_publications.py
> +def test_duplicated_dataset(client: TestClient, engine: Engine):
"dataset" -> "publication"
Same for some variable names

2023-03-16 13:38 UTC, josvandervelde commented on scripts/run_apiserver_dev.sh
Did you delete this file on purpose?

2023-03-16 13:38 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_publication_connector.py
> +            doi=publication_json["doi"], title=publication_json["metadata"]["title"],node=publication.node,
The formatting of this file is not conform black. See https://github.com/psf/black for info: black makes it easier to work together, by making sure that everyone uses the same coding style.
 
You can fix this by running `pre-commit install`. Then, before each commit, black, flake, mypy and the unittests are run. This also prevents commits with red unittests.

2023-03-16 14:08 UTC, arejula27 commented on scripts/run_apiserver_dev.sh
Was a problem with git, i will rescue it

2023-03-20 09:26 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
Yes,  i think it is possible, how can i implement the pagination?

2023-03-20 09:59 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
I meant using `size` and `page` (see https://developers.zenodo.org/#list36). Without the `size` param, only 2 results are returned in as `hits` in the json, in my test at least. So I think you'll have to do something like `size=1000` and repeatedly querying the url while incrementing the `page`.
There might be a better way / other endpoint, this is just based on a quick look a the documentation

2023-03-20 10:43 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
![image](https://user-images.githubusercontent.com/46299278/226316784-b835dee0-1950-4ded-a3ef-f9a9feadbc87.png)
I got 2876356 hits,i will try to filter by type but i dont think pagination is a problem

2023-03-20 10:45 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
On the API es mocked with only 2 hits, maybe thats the problem 😵‍💫

2023-03-20 11:06 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
Yes, i have just see it. The max size per page is 10000.  Do you think is a correct solution returning all the list or it is better to have pagination as zenodo? 
I have just change the code to a real request because i returned alwys the same results: 
![image](https://user-images.githubusercontent.com/46299278/226321976-8ba4dc93-f4b2-4144-9cc0-31a193a89f29.png)

2023-03-20 11:27 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
![image](https://user-images.githubusercontent.com/46299278/226326406-e9b4e690-74a7-477f-b80c-fa4ddbe60c18.png)
Look weird... I dont understand why i can only get the first 10000 results :s

2023-03-20 11:29 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
![image](https://user-images.githubusercontent.com/46299278/226326905-eded6dad-1cef-45fb-a414-e96ab1363c71.png)
Looks like it only posible to get the first 10000 results :c

2023-03-20 11:46 UTC, arejula27 commented on src/connectors/zenodo/zenodo_publication_connector.py
> +        yield from [
Agree

2023-03-20 14:11 UTC, arejula27 commented
I have just added the endpoint /node/<node>/publications that sends a 501 error.

2023-03-21 07:50 UTC, josvandervelde approved these changes

2023-03-28 07:22 UTC, merged