Feature/ai builder connector
aiondemand/AIOD-rest-api pull request #408
Opened 2024-12-05 10:59 UTC by AdrianAlcolea

## Change
New connector for the AIBuilder platform

## How to Test
There are unitary test created for it.
To test the actual functionality you need to add a valid API_TOKEN (from a user of the platform) to the 'override.env' file and use the 'aibuilder' profile when launching docker compose. Then you will see new ml_models added to the platform (you can search selecting the 'aibuilder' platform).

## Checklist
The only thing I didn't do is to add an explanation on the README (in general I see that there are no such explanations for the use of other connectors, but maybe the TOKEN thing should be commented). I guess we can discuss this on the PR and decide if it needs some explanation.

2024-12-18 14:33 UTC, PGijsbers requested changes
Don't have it working yet (probably misconfigured my API_TOKEN?), so have to try that tomorrow. Here's already some changes though. Assuming it otherwise works I think that's all that really needs to be addressed.

2024-12-18 14:33 UTC, PGijsbers commented on .env
> +API_TOKEN=""
Probably better to update this to `AIBUILDER_API_TOKEN`, there are likely going to be more API tokens.

2024-12-18 14:33 UTC, PGijsbers commented on connectors/aibuilder/Dockerfile
> +USER root
```suggestion
USER root
RUN apt-get update
```

cron was not installable for me otherwise

2024-12-18 14:33 UTC, PGijsbers commented on docker-compose.yaml
> +      - ./connectors/aibuilder/:/opt/connectors/script
Please include the default scripts directly in the image, optionally provide mounted scripts for live updates in the `docker-compose.dev.yaml`. This makes it so that when running without `USE_LOCAL_DEV`, you do not accidentally include local changes (provided images were built with a clean slate). Mounting the data directory (for writing logs) can stay, of course. See for example the zenodo connector.

2024-12-18 14:33 UTC, PGijsbers commented on connectors/aibuilder/Dockerfile
> +COPY entry.sh /opt/connectors/script/entry.sh
Move these commands to below the installation of cron. That way, when rebuilding the image when these files are updated, you can use your build cache to avoid having to re-download/install cron.

2024-12-18 14:33 UTC, PGijsbers commented on src/connectors/aibuilder/aibuilder_mlmodel_connector.py
> +TOKEN = os.getenv("API_TOKEN", "")
Please add an immediate and clear error when the `API_TOKEN` is not set.

2024-12-18 14:33 UTC, PGijsbers commented on src/connectors/aibuilder/aibuilder_mlmodel_connector.py
> +            msg = response.json()["error"]["message"]
This errors when the content of the response is not JSON. I found that for the 401: UNAUTHORIZED response, the server does not return JSON, so the connector would crash.

2024-12-18 16:28 UTC, AdrianAlcolea commented on src/connectors/aibuilder/aibuilder_mlmodel_connector.py
> +            msg = response.json()["error"]["message"]
I added a try - except block returning a record error (it is maybe too generic error for that, but I think it is the proper way in this context to return it)

2024-12-18 16:55 UTC, AdrianAlcolea commented
I made all the modifications, also added an __init__ method to be able of passing a non-empty TOKEN for the tests.

2024-12-19 09:02 UTC, PGijsbers commented on src/connectors/aibuilder/aibuilder_mlmodel_connector.py
> +            msg = response.json()["error"]["message"]
The problem is not with the request itself (though I guess there can also be errors there). The request is successful but it will have status `401: UNAUTHORIZED` and content `b'authentication: null'` or something similar. The latter is not JSON, so the `response.json()` call below will result in an error.

2024-12-19 09:05 UTC, PGijsbers commented on docker-compose.yaml
> +    env_file: .env
Hm. I thought I left a comment about this earlier. It should not be necessary to forward the entire env file to the docker container. you should be able to remove that line. If things break, then you'd need to see which environment variable is missing and forward it with "environment" instead.

2024-12-19 10:34 UTC, AdrianAlcolea commented on docker-compose.yaml
> +    env_file: .env
Oh, that's true. I started it before the 'override.env' modification =P

2024-12-19 10:40 UTC, AdrianAlcolea commented on src/connectors/aibuilder/aibuilder_mlmodel_connector.py
> +            msg = response.json()["error"]["message"]
Ah, ok. I took this behaviour from the openml connectors, so maybe we should revise them too. I am looking now at the zenodo one and I will change the approach to that one

2024-12-19 11:46 UTC, AdrianAlcolea commented
I modified the code to handle the responses that are correct but not a 200, added an specific error message for the 401 error and made a new unitary test for it. Also removed the .env file from docker compose.

2024-12-20 08:28 UTC, PGijsbers approved these changes
LGTM

2024-12-20 08:29 UTC, merged