Docs/connectors
aiondemand/AIOD-rest-api pull request #427
Opened 2024-12-23 14:05 UTC by PGijsbers

## Change

Further centralizes the different documentation files across the repository into one more structured documentation site.
It should be easier to navigate, find, and present information with the mkdocs plugins and on-page hierarchies.
I generally updated and expanded a lot of information, but in some cases I preferred to withhold since it would be better to improve the docs overtime or to have people more familiar with a particular service write/update the docs.

## How to Test

## Checklist
- [ ] Tests have been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] Documentation has been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] A self-review has been conducted checking:
  - No unintended changes have been committed.
  - The changes in isolation seem reasonable.
  - Anything that may be odd or unintuitive is provided with a GitHub comment explaining it (but consider if this should not be a code comment or in the documentation instead).
- [ ] All CI checks pass before pinging a reviewer, or provide an explanation if they do not.

## Related Issues

2025-01-29 16:38 UTC, Taniya-Das commented on docs/README.md
Might be good to also mention HuggingFace here. 
"It collects metadata from platforms such as [_Zendodo_](https://zenodo.org), [_OpenML_](https://openml.org) and [_HuggingFace_](https://huggingface.co/)"

2025-01-30 12:54 UTC, Taniya-Das commented on docs/README.md
The rest looks good to me.

2025-01-30 12:54 UTC, Taniya-Das approved these changes

2025-01-30 16:04 UTC, AdrianAlcolea requested changes
There was one property missing (the `CaseStudy` entity used for the example doesn't require it).
In general is pretty good and descriptive =)

2025-01-30 16:04 UTC, AdrianAlcolea commented on docs/developer/elastic_search.md
> +    This is a short-running services that only runs on startup, exiting when its done.
```suggestion
    This is a short-running service that only runs on startup, exiting when its done.
```

2025-01-30 16:04 UTC, AdrianAlcolea commented on docs/developer/elastic_search.md
> +
````suggestion

```python
    @property
    def extra_indexed_fields(self) -> set[str]:
        return {"headline", "alternative_headline"}
```

The `extra_indexed_fields` property contains the fields of the entity that should be included in the index other than the `global_indexed_fields` found in the `SearchRouter` class.

````

2025-01-30 17:10 UTC, mrorro commented
How to Test
To build the documentation locally, after checkout out this branch:
- Install mkdocs-material and mkdocs-section-index plugin: python -m pip install mkdocs-material mkdocs-section-index
- Run the documentation server: python -m mkdocs serve
- Browse local documentation at: http://127.0.0.1:8000/docs/

In my case I also had to install mkdocs-section-index. I'd also suggest adding the search plugin to mkdocs.yaml

2025-01-31 09:26 UTC, PGijsbers commented
Thanks Marco, I had added the dependency to pyproject.toml, but somehow forgot to mention it in the PR. I added the search plugin, as suggested :)

2025-02-04 15:19 UTC, mrorro commented on docs/developer/authentication.md
Replace from ## Hosting and External Identity Providers to the end with 
## Using External Identity Providers 

There are two ways to integrate external identity providers (e.g. Google, [EGI Check-in](https://docs.egi.eu/users/aai/check-in/)). 

Create both a private and a public client in the external provider (this step is required for both options below).

### Option 1: Update the configuration files
   - Replace `KEYCLOAK_CLIENT_SECRET` in `.env.ovverride` with the value provided by the external IdP.
   - Update `server_url`, `client_idr`, `client_id_swagger` `openid_connect_url` and `scopes` in `./src/config.override.toml`.
   - In this setup, the Keycloak container is not required and can be shut down.
### Option 2: use keycloak as an identity broker
   - Details can be found in the Keycloak documentation: [Integrating identity providers](https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker). 
   - This method allows to configure multiple IdPs.
  
[//]: # (Should include information on how to run it locally then...)

## Roles

Roles identify a type or category of user and determine their access and permissions within applications.
Currently, only the ` edit_aiod_resources` role is defined, granting users the ability to upload and edit resources.
Note that roles may be used for services other than the metadata catalogue.

[//]: # ( Are we missing roles? Check admin console. Are all roles still relevant? delete if not)

## Verifying Keycloak is Working

To verify the Keycloak service is configured correctly using the Swagger interface, follows these steps:

 1. Open your browser and go to http://$HOSTNAME
 2. Go to `/authorization_test`, click on `try it out` and `execute`. 
    - You should get an `Error: Unauthorized`
 3. Log in:
    - Click the `Authorize` button in the top-right corner.
    - Select `OpenIdConnect (OAuth2, authorization_code with PKCE)`.
    - Click `Authorize` and log in using any available identity provider. 
 4. Return to `/authorization_test`, click `try it out` and then `execute` again.

If authentication is succesful, the request should now be authtorised.

2025-02-06 09:45 UTC, merged