Zenodo aio intergation
aiondemand/AIOD-rest-api pull request #49
Opened 2023-05-23 14:19 UTC by arejula27

2023-05-24 07:08 UTC, josvandervelde requested changes
It would be good to run pre-commit and to add tests.

As noted in one of the comments, I would suggest keeping the different resources separate for now, by fetching everything, and filtering. We can change it later.

2023-05-24 07:08 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_connector.py
> +        #Get creator name
This is more of a personal preference, but I don't think these comments are helpful.
"Comment the why, not the what", is a good rule to follow when writing comments, I think.
It's easy to see here that you're getting the creators name. If it would not be easy, you're attribute naming should be improved (not the case here).

It seems that you're using your comments more to divide the code into sub-parts. If that's really the goal, I think that separate functions would be better. Here it's not needed though, I'd say. I'd suggest just removing these comments, but as I said, it's partly up to personal preference.

2023-05-24 07:08 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_connector.py
> +        print("Software")
I don't think we should have such prints in our code. Flake will also complain about it. If this is really necessary, consider using a log.info / log.debug. Or Just add a TODO.

2023-05-24 07:08 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_connector.py
> +        self._process_records_from_datetime(sickle,date)
You omitted the yield. Now you don't return anything

2023-05-24 07:08 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_connector.py
> +            doi=publication_json["doi"],
You're not using `fetch` in `fetch_all`. Maybe because `fetch` is for Publications, and `fetch_all` for Datasets. When you finish this code, it would be nice to reuse code, I think

2023-05-24 07:21 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        print("Software")
This comment is just provisional it will be changed by real code

2023-05-24 07:22 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        self._process_records_from_datetime(sickle,date)
Yes, that is a doubt I have. This function would return different AIoResources instead of a dataset or code

2023-05-24 09:27 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        identifier = platform_identifier
This is a deprecated function from months ago, currently i am only focus on gathering all data.
This function might be also deleted from the abstract class as long as the conncetors only retrieve data, dont forward requests.

2023-05-24 09:29 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        creator =""
I will do pre-commit once i have a final pull reuqtes (now is only a draft), because im doing many changes and it making all the time pre-commit is not needed. However i can run it each time i ask you for review if you prefer

2023-05-24 09:32 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        self._process_records_from_datetime(sickle,date)
Fixed, only return dataset

2023-05-24 09:33 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +            doi=publication_json["doi"],
Im using the same file as the Zenodo publication connector. I will change all the publication related things to dataset. However im currently focus on the fetch all function

2023-05-24 09:35 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        #Get creator name
Yes, i used as separators haha. I think that it is important to have a standard style so if comments are not used as separator in the project i will remove them.

2023-05-24 09:47 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +            date_published = datetime.strptime(date_string, date_format)
If is list takes number 0

2023-05-24 09:59 UTC, arejula27 commented on src/connectors/zenodo/zenodo_connector.py
> +        if(isinstance(record["creators"]["creator"], list)):
Each field has specific ways to handle it, it is better to duplicate code

2023-05-24 10:21 UTC, arejula27 commented
Make may changes following your suggestions, i will look for how to mock this protocol

2023-05-25 08:13 UTC, josvandervelde reviewed
Some additional comments. It's a step in the good direction, I think :)

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +        if isinstance(record["publisher"], str):
Why do you ignore it if it isn't a string? Is there no information then?

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +        date_format = "%Y-%m-%d"
This would be better as `DATE_FORMAT` global variable (at start of the file), I think.

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            description=description[:500],
If the description is longer, I would prefer making it clear to the user. Maybe `description[:494] + " [...]"` if it's longer than 500 characters?

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            **{
It would be more normal to write this as 
`sk.ListRecords(metadataPrefix="oai_datacit", from: dt.isoformat())`.

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +    def _retrieve_dataset_from_datetime(self, sk: Sickle, dt: datetime):
A return type hint would be nice.

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +                keywords = [item for item in record["subjects"]["subject"] if isinstance(item, str)]
You're ignoring the keywords that are not strings. Why? What can they be? 
If you do not expect them to exist, it would be better to raise an error. Now we might miss data.

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            elif isinstance(record["subjects"]["subject"], list):
You're using `elif`. Adding an `else` would help: we want an error if there is information in another format than we expect. So I would suggest either changing the elif into an else, or adding an else with a `raise Exception`.

This goes for other fields here as well.

2023-05-25 08:13 UTC, josvandervelde commented on src/tests/resources/connectors/zenodo/article_example.xml
> +						<rights rightsURI="https://creativecommons.org/licenses/by/4.0/legalcode">Creative Commons Attribution 4.0 International</rights>
This should go into `dataset.license`

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            name=title[:150],
you're not adding platform or platform_identifier.
I'd suggest using the DOI as platform_identifier

2023-05-25 08:13 UTC, josvandervelde commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +                if element.get("@dateType") == "Issued":
Are there other dataTypes, beside Issued? Maybe modified or published? would be interesting to add.

2023-05-25 08:14 UTC, arejula27 commented on src/tests/connectors/zenodo/test_get_publication_zenodo.py
> +    # Aquí puedes simular los registros que deseas devolver
hahah sorry

2023-05-25 08:17 UTC, arejula27 commented on src/tests/connectors/zenodo/test_get_publication_zenodo.py
> +    assert dataset.date_published == datetime(2023, 5, 6)
okay, i will expand it

2023-05-25 08:18 UTC, arejula27 commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +        xml_dict = xmltodict.parse(xml_string)
I use the dictionary for extracting all fields, not just the type. There are complex fields, i think this is the correct way

2023-05-25 08:19 UTC, arejula27 commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +                keywords = [item for item in record["subjects"]["subject"] if isinstance(item, str)]
There is no a schema defined, the correct ones are dict and str, it is only for avoiding errors but if you prefer i can delete the conditional

2023-05-25 08:20 UTC, arejula27 commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            elif isinstance(record["subjects"]["subject"], list):
sure

2023-05-25 08:20 UTC, arejula27 commented on src/tests/resources/connectors/zenodo/article_example.xml
> +						<rights rightsURI="https://creativecommons.org/licenses/by/4.0/legalcode">Creative Commons Attribution 4.0 International</rights>
Uri or name?

2023-05-25 08:22 UTC, arejula27 commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +                if element.get("@dateType") == "Issued":
I didnt found other dates, but the publication date is named Issued, i dont know why. The problem is that this schemas dont have a structure, each dataset have a different one.

2023-05-29 07:56 UTC, josvandervelde reviewed
Looks good!
There were still a couple of points left open from the last review.

2023-05-29 07:56 UTC, josvandervelde commented on src/tests/resources/connectors/zenodo/article_example.xml
> +<?xml version="1.0" ?>
Are`article_example.xml`, `code_example.xml`, `dataset_example.xml` and `list_records copy.xml` used?
If not, they can be removed

2023-05-29 09:02 UTC, arejula27 commented on src/connectors/zenodo/zenodo_dataset_connector.py
> +            **{
it doesnt work, syntax error

2023-05-29 13:24 UTC, josvandervelde approved these changes

2023-05-29 13:25 UTC, merged